### PR TITLE
[MOBILE-273] Add CI script.

### PR DESCRIPTION
**Pull request by BrianBatchelder**
### What do these changes do?
Add a Continuous Integration (CI) script to our react-native repo.

### Why are these changes necessary?
We want to run CI on all pushes to the react-native repo. We want it to also be run locally.

### How did you verify these changes?
Ran it locally. Also tested on CI server.

### Anything else a reviewer should know?
I also fixed some typos and committed the changes to a couple of lock files that were updated by the build.

### CODE REVIEW

**Comment by rlepinski** [comment]
@BrianBatchelder Make sure no promotion secrets are exposed in the PR trigger.

**Comment by rlepinski** [comment]
👍

**Comment by BrianBatchelder** [comment]
@rlepinski: should be ok. “Expose for Pull Requests?” = NO.

**Comment by marc-scig** [comment]
🚶

**Pull request merged**
