### PR TITLE
Fabric support

### PR DESCRIPTION
**Pull request by j-piasecki**
### What do these changes do?

This PR adds support for the new React Native architecture, mainly the fabric renderer.

### Anything else a reviewer should know?

I've had some troubles with testing the FabricExample app due to the requirement of keys.

### CODE REVIEW

**Comment by rlepinski** [comment]
@j-piasecki thanks for the PR. Is this ready to be merged?

**Comment by rlepinski** [comment]
Could you sign the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScErfiz-fXSPpVZ9r8Di2Tr2xDFxt5MgzUel0__9vqUgvko7Q/viewform) ?

**Comment by j-piasecki** [comment]
@rlepinski As I've mentioned in the description, I've had some trouble testing the FabricExample app due to the requirement of keys. If you could verify that it works correctly, then I believe it's ready.

**Comment by j-piasecki** [comment]
As a side note, I've noticed that `enableUserPushNotifications` method has been removed on the iOS module but it's still there on Android and in the JS code. Is that method going to be removed or was that by mistake?

**Comment by rlepinski** [comment]
@j-piasecki I tested iOS, ill test Android next. The next branch has a few other issues that are unrelated to your changes. Ill verify Android and merge today, then get to work on fixing up the plugin.

Looks like to support Turbo Modules with swift, I need to revert some of my swift rewrite. I am in the process of that and should hopefully have an update today.

**Pull request merged**
